spring.application.name=bankingsystem
server.port=8080

#MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/bankdb
spring.datasource.username=root
spring.datasource.password=Harsha@1805
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#Email Configuration - Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.prot=587
spring.mail.username=harshavardhanreddycharlapalli@gmail.com
spring.mail.password=frkbvmdfzaongwdy
spring.email.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.able=true
srping.mail.properties.mail.smtp.starttls.required=true
# Use environment variables for production
# Railway sets these automatically
spring.datasource.url=${DATABASE_URL:jdbc:mysql://localhost:3306/bankdb}
spring.datasource.username=${DATABASE_USERNAME:root}
spring.datasource.password=${DATABASE_PASSWORD:Harsha@1805}
spring.mail.username=${MAIL_USERNAME:harsha.charlapally@gmail.com}
spring.mail.password=${MAIL_PASSWORD:frkbvmdfzaongwdy}
spring.jpa.hibernate.ddl-auto=update
server.port=${PORT:8080}